BANNER_NOT_AN_IMAGE = 0
BANNER_INVALID_SIZE = 2
BANNER_VALID = 1
BANNER_SIZE = (900, 1300)

# RESOURCES
EMPTY_BANNER = 'res/banner.png'
EMPTY_TABS_FOLDER = 'res/Metanet'

WARNING_TITLE = "Warning"
TABS_EXIST_WARNING_MESSAGE = "These tabs already exist:\n\n"
TABS_EXIST_WARNING_QUESTION = "\nDo you want to replace them?"
